local EMBEDDED_SPELLS = {
    bard = {
        [70] = { 'Voice of the Vampire', "Vulka's Chant of Flame", "Vulka's Lullaby" },
        [69] = { 'Verse of Vesagran', "Eriki's Psalm of Power", 'Chorus of Life' },
        [68] = { 'War March of Muram', "Vulka's Chant of Poison", "Yelhun's Mystic Call", 'Dirge of Metala' },
        [67] = { "Luvwen's Lullaby", "Zuriki's Song of Shenanigans", 'Cantata of Life', "Vulka's Chant of Frost", "Angstlich's Wail of Panic" },
        [66] = { "Luvwen's Aria of Serenity", "Vulka's Chant of Disease", 'Bellow of Chaos' },
    },
    beastlord = {
        [70] = { 'Spirit of Rashara', 'Festering Malady', 'Ferocity of Irionu', "Sha's Legacy" },
        [69] = { 'Glacier Spear', 'Feral Vigor', 'Spiritual Ascendance', 'Feral Guard' },
        [68] = { 'Spirit of Alladnu', 'Growl of the Beast', 'Spirit of Irionu' },
        [67] = { "Muada's Mending", 'Focus of Alladnu', 'Spiritual Vitality' },
        [66] = { 'Healing of Mikkily', 'Chimera Blood' },
    },
    berserker = {
        [70] = { 'Vengeful Flurry Discipline', 'Bloodthirst' },
        [69] = { 'Baffling Strike' },
        [68] = { 'Mind Strike', 'Unflinching Will' },
        [67] = { 'Crippling Strike' },
        [66] = { 'Axe of the Destroyer', 'Unpredictable Rage Discipline' },
    },
    cleric = {
        [70] = { 'Placate', 'Silent Dictation', 'Armor of the Pious', "Balikor's Mark", 'Hand of Conviction' },
        [69] = { 'Mark of the Blameless', 'Word of Vivification', 'Calamity', 'Aura of Devotion', 'Yaulp VII', 'Chromastrike' },
        [68] = { 'Unswerving Hammer of Retribution', 'Hammer of Reproach', 'Pious Light', 'Sound of Divinity', 'Desolate Undead' },
        [67] = { 'Sermon of Reproach', 'Conviction', 'Blessing of Devotion', 'Pious Elixir', 'Reproach', 'Panoply of Vie' },
        [66] = { 'Confidence', 'Pious Remedy', 'Symbol of Balikor', 'Ward of Valiance', 'Shock of Wonder', 'Sun Cloak', 'Revulsion of Death' },
    },
    druid = {
        [70] = { 'Hungry Vines', "Nature's Beckon", 'Circle of Nettles', 'Blessing of Steeloak', 'Glitterfrost', 'Mask of the Wild' },
        [69] = { 'Blessing of Oak', 'Oaken Guard', 'Solstice Strike', 'Vengeance of the Sun' },
        [68] = { 'Steeloak Skin', 'Chlorotrope', 'Wasp Swarm', 'Nettlecoat', 'Desolate Summoned', 'Cloak of Nature' },
        [67] = { "Nature's Serenity", 'Immolation of the Sun', "Lion's Strength", "Sun's Corona", 'Glacier Breath', 'Nettle Shield' },
        [66] = { 'Oaken Vigor', 'Stormwatch', 'Tempest Wind', 'Earth Shiver', 'Instinctual Terror' },
    },
    enchanter = {
        [70] = { 'Circle of Alendar', 'True Name', 'Hastening of Salik', 'Voice of Clairvoyance', "Focus Ornate Spellcaster's Essence" },
        [69] = { 'Arcane Noose', 'Wake of Felicity', 'Mayhem', 'Color Snap', 'Euphoria', 'Desolate Deeds', "Focus Mass Elaborate Spellcaster's Essence" },
        [68] = { 'Compel', 'Clairvoyance', 'Wall of Alendar', 'Psychosis', 'Circle of Dreams' },
        [67] = { 'Felicity', 'Rune of Salik', 'Placate', 'Speed of Salik', 'Anxiety Attack' },
        [66] = { 'Synapsis Spasm', 'Ethereal Rune', 'Mystic Shield', "Salik's Animation", 'Cloud of Indifference' },
    },
    magician = {
        [70] = { 'Circle of Fireskin', 'Star Scream', 'Child of Earth', 'Elemental Simulacrum', 'Shock of Myriad Minions' },
        [69] = { 'Burning Earth', 'Desolate Summoned', 'Renewal of Jerikor', 'Bulwark of Calliav', 'Elemental Fury' },
        [68] = { 'Phantom Shield', 'Summon Pouch of Jerikor', 'Blade Strike', 'Child of Fire', 'Pyrilen Skin', 'Elemental Fury' },
        [67] = { 'Summon Staff of the North Wind', 'Summon Dagger of the Deep', 'Rain of Jerikor', 'Child of Water', 'Summon Sphere of Air', 'Summon Crystal Belt' },
        [66] = { "Summon Calliav's Runed Mantle", 'Fireskin', 'Summon Fireblade', "Summon Calliav's Jeweled Bracelet", "Summon Calliav's Spiked Ring", "Summon Calliav's Glowing Bauble", "Summon Calliav's Steel Bracelet", 'Elemental Aura', 'Child of Wind', 'Bolt of Jerikor', "Summon Calliav's Platinum Choker" },
    },
    monk = {
        [70] = { 'Rapid Kick Discipline' },
        [69] = { 'Phantom Cry' },
        [68] = { 'Counterforce Discipline' },
        [66] = { 'Dreamwalk Discipline' },
    },
    necromancer = {
        [70] = { 'Chaos Venom', 'Dark Possession', 'Dark Assassin', 'Desolate Undead', 'Word of Chaos' },
        [69] = { 'Dull Pain', 'Dark Hold', 'Dark Salve', 'Bulwark of Calliav', 'Pyre of Mori' },
        [68] = { 'Scent of Midnight', 'Desecrating Darkness', 'Shadow of Death', 'Fang of Death' },
        [67] = { 'Soulspike', 'Grip of Mori', 'Glyph of Darkness', 'Lost Soul', 'Dark Nightmare', 'Unholy Howl' },
        [66] = { 'Acikin', 'Shadow Guard', 'Chaos Plague', 'Eidolon Howl' },
    },
    paladin = {
        [70] = { 'Wave of Piety', 'Affirmation' },
        [69] = { 'Hand of Direction', 'Armor of the Champion', 'Pious Cleansing', 'Bulwark of Piety', "Brell's Brawny Bulwark" },
        [68] = { 'Pious Fury', 'Light of Piety', 'Serene Command', "Jeron's Mark", 'Last Rites' },
        [67] = { "Crusader's Purity", 'Silvered Fury', 'Spurn Undead', 'Symbol of Jeron' },
        [66] = { 'Direction', 'Touch of Piety', 'Force of Piety' },
    },
    ranger = {
        [70] = { 'Onyx Skin', 'Ward of the Hunter', 'Call of Lightning' },
        [69] = { "Nature's Denial", 'Howl of the Predator', 'Hearth Embers', "Nature's Balance" },
        [68] = { 'Briarcoat', 'Frost Wind', "Hunter's Vigor" },
        [67] = { 'Locust Swarm', 'Sylvan Water', 'Guard of the Earth', 'Strength of the Hunter' },
        [66] = { 'Nature Veil', 'Flame Snap', 'Shield of Briar' },
    },
    rogue = {
        [70] = { 'Frenzied Stabbing Discipline' },
        [69] = { 'Daggerfall' },
        [68] = { 'Deadly Aim Discipline' },
        [66] = { 'Imperceptible Discipline' },
    },
    shadowknight = {
        [70] = { 'Theft of Hate', 'Touch of the Devourer', 'Cloak of Discord' },
        [69] = { 'Rune of Decay', 'Pact of Decay', 'Spear of Muram', 'Dread Gaze' },
        [68] = { 'Theft of Pain', 'Blood of Inruku', 'Son of Decay', 'Scythe of Inruku' },
        [67] = { 'Touch of Inruku', "Inruku's Bite", 'Shroud of Discord', 'Terror of Discord', 'Shadow Howl' },
        [66] = { 'Blood of Discord', 'Dark Constriction', 'Bond of Inruku', 'Soulless Terror' },
    },
    shaman = {
        [70] = { 'Vindictive Spirit', 'Talisman of Might', 'Blood of Yoppa', 'Talisman of Wunshi', 'Spiritual Serenity', 'Champion' },
        [69] = { 'Talisman of Fortitude', 'Talisman of Perseverance', 'Ice Age', 'Pure Spirit', 'Curse of Sisslak', 'Balance of Discord' },
        [68] = { "Yoppa's Mending", "Wunshi's Focusing", 'Spirit of Fortitude', 'Talisman of Sense', "Yoppa's Rain of Venom", 'Pained Memory' },
        [67] = { "Farrel's Companion", 'Ancestral Bulwark', 'Spirit Veil', 'Spirit of Might', 'Breath of Wunshi' },
        [66] = { 'Spirit of Sense', "Yoppa's Spear of Venom", 'Putrid Decay', 'Spirit of Perseverance', 'Crippling Spasm' },
    },
    warrior = {
        [70] = { 'Shocking Defense Discipline' },
        [69] = { 'Throat Jab Rk. II' },
        [68] = { 'Brutal Onslaught Discipline Rk. II' },
        [66] = { 'Aura of Runes Discipline' },
    },
    wizard = {
        [70] = { 'Circle of Thunder', 'Telekara', 'Bulwark of Calrena', 'Gelid Rains', 'Corona Flare' },
        [69] = { 'Ether Ward', 'Meteor Storm', 'Spark of Ice', 'Gelidin Comet', "Solist's Frozen Sword" },
        [68] = { 'Firebane', 'Ether Skin', 'Spark of Thunder', 'Thundaka', 'Wildmagic Burst' },
        [67] = { 'Lightningbane', 'Circle of Fire', 'Phase Walk' },
        [66] = { 'Icebane', 'Ether Shield', 'Tears of the Sun', 'Spark of Fire' },
    },
}